DATASET_PATH = 'data\2cls_spam_text_cls.csv'
SEED = 42

RANDOM_STATE = 42
TEST_SIZE = 0.2

TFIDF_MAX_FEATURES = 8000
TFIDF_MIN_DF = 3
TFIDF_MAX_DF = 0.9
TFIDF_NGRAM_RANGE = (1, 2)

NB_ALPHA = 0.5

AUGMENT_SPAM = True
AUGMENT_TIMES_PER_SAMPLE = 2
AUGMENT_DELETE_PROB = 0.15

EMBEDDING_MODEL_NAME = "intfloat/multilingual-e5-base"
EMBEDDING_BATCH_SIZE = 64

FAISS_USE_COSINE = True
KNN_K = 5

GRADIO_SERVER_NAME = "0.0.0.0"
GRADIO_SERVER_PORT = 7860

